### ISSUE TITLE
bdf test failures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#166]
```
python all_tests.py in pynastran-read-only/pyNastran/bdf/test
using r2297

======================================================================
ERROR: test_mass_shell_1 (pyNastran.bdf.test.unit.test_mass.TestMass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/unit/test_mass.py", line 79, in test_mass_shell_1
    self.verify_pcomp_element(quad, mass, area, centroid, normal)
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/unit/test_mass.py", line 17, in verify_pcomp_element
    self.assertAlmostEqual(element.Mass(), mass, msg='mass=%s expected=%s' % (element.Mass(), mass))
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/cards/elements/shell.py", line 133, in Mass
    return self.pid.MassPerArea() * self.Area()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

======================================================================
ERROR: test_PCOMP_01 (pyNastran.bdf.test.cards.test_shells.TestShells)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_shells.py", line 236, in test_PCOMP_01
    self.assertAlmostEqual(p.Theta(0), 0.)
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/cards/properties/shell.py", line 50, in Theta
    return self.get_theta()
TypeError: get_theta() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_PCOMP_02 (pyNastran.bdf.test.cards.test_shells.TestShells)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_shells.py", line 365, in test_PCOMP_02
    self.assertAlmostEqual(p.Theta(0), 0.)
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/cards/properties/shell.py", line 50, in Theta
    return self.get_theta()
TypeError: get_theta() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_PSHELL_01 (pyNastran.bdf.test.cards.test_shells.TestShells)
tests a CQUAD4 and a PSHELL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_shells.py", line 184, in test_PSHELL_01
    self._make_ctria3(model, rho, nu, G, E, t, nsm)
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_shells.py", line 117, in _make_ctria3
    self.assertAlmostEquals(ctria3.Mass(), mass)
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/cards/elements/shell.py", line 133, in Mass
    return self.pid.MassPerArea() * self.Area()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

======================================================================
FAIL: test_pbar_01 (pyNastran.bdf.test.cards.test_bars.TestBars)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_bars.py", line 21, in test_pbar_01
    pbar = PBAR(card2)
AssertionError: AssertionError not raised

======================================================================
FAIL: test_pbar_02 (pyNastran.bdf.test.cards.test_bars.TestBars)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/cards/test_bars.py", line 57, in test_pbar_02
    self.assertEqual(pbar.K1, 1e8)
AssertionError: None != 100000000.0

======================================================================
FAIL: test_include_end (pyNastran.bdf.test.unit.test_read_write.TestReadWrite)
this test fails
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/bdf/test/unit/test_read_write.py", line 128, in test_include_end
    self.assertEquals(len(model.nodes), 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 134 tests in 14.424s

FAILED (failures=3, errors=6)

```

Original issue reported on code.google.com by `nils...@googlemail.com` on 12 Oct 2014 at 8:51

**Comment by SteveDoyle2** [comment]
The bug is fixed; closing...

v0.7dev version pushed
Master pushed
