### ISSUE TITLE
BDF reader should accept non-ascii chars in comments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#168]
```
What is the new feature/capability that you'd like?

BDF reader should accept non-ascii characters in comment cards and string 
fields like title and subtitle.

Why is it useful?

Some decks may contain non-ascii characters (e.g., degree symbol). Presently 
these characters need to be removed and replaced with ascii placeholders. 
Otherwise, these characters cause an error in the BDF.read_bdf method, e.g., 

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\gui\gui_qt.py", line 1002, in on_load_geometry
    has_results = load_function(infile_name, self.last_dir)
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\converters\nastran\nastranIO.py", line 99, in load_nastran_geo
metry
    model.read_bdf(bdf_filename, include_dir=dirname, punch=punch, xref=True)
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\bdf\bdf.py", line 748, in read_bdf
    self._read_bulk_data_deck()
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\bdf\bdf.py", line 1182, in _read_bulk_data_deck
    (lines, comment) = self._card_streams[self._ifile].next()
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\bdf\bdf.py", line 1067, in _stream_card
    (i, line, comment) = self._get_line()
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\bdf\bdf.py", line 1239, in _get_line
    return self._line_streams[self._ifile].next()
  File "C:\Anaconda\lib\site-packages\pynastran-0.7.0_dev-py2.7.egg\pyNastran\bdf\bdf.py", line 1253, in _stream_line
    line = line.rstrip('\t\r\n ')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 29: 
ordinal not in range(128)


List a sample API for the new functionality:
example:  nodeObject = mesh.getNode(nodeID)

 * use unicode for comments and user-defined string varibales
 * maybe use try/except/finally to parse these lines in the deck?

Any other requirements on the functionality?


```

Original issue reported on code.google.com by `jeffrey....@gmail.com` on 29 Oct 2014 at 1:02

**Comment by SteveDoyle2** [comment]
Similar to #202, unicode will be handled using:

    model = BDF()
    model.read_bdf(bdf_filename, encoding='latin-1')

which will be the encoding unless, the BDF contains:

    $ pyNastran: encoding=latin-1
    $ pyNastran: encoding=utf-8

at the top of the file.  Don't put two encodings.  It won't be checked for :) and the last one will take priority.

**Comment by SteveDoyle2** [comment]
In bdf.py, the main() function shows how to use unicode properly.
