### ISSUE TITLE
AttributeError: 'F06' object has no attribute 'subtitles'

### ISSUE THREAD

**Issue by SteveDoyle2** [SteveDoyle2/pyNastran#177]
Per nils

python all_tests.py in pynastran-read-only/pyNastran/f06/test using r2632 

======================================================================
ERROR: test_bar3truss_1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 268, in test_bar3truss_1
    f06 = self.run_model(bdfname, f06name, op2name, f06_has_weight=True)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_beam_modes_1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 226, in test_beam_modes_1
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, f06_has_weight=True)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_cbush_1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 303, in test_cbush_1
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_complex_displacement (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 440, in test_complex_displacement
    f06 = self.run_model(bdfname, f06name1, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_complex_tets_1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 214, in test_complex_tets_1
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_eigenvectors1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 462, in test_eigenvectors1
    f06 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_eigenvectors2 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 482, in test_eigenvectors2
    f06 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_failure_index (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 390, in test_failure_index
    f06 = self.run_model(bdfname, f06name1, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_plate_openmdao (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 416, in test_plate_openmdao
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, dynamic_vars=dynamic_vars, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_plate_vonmises (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 497, in test_plate_vonmises
    (bdf, f06, op2) = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_solid_shell_bar_1 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 317, in test_solid_shell_bar_1
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

======================================================================
ERROR: test_solid_shell_bar_2 (pyNastran.f06.test.f06_unit_tests.TestF06)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 349, in test_solid_shell_bar_2
    bdf, f06, op2 = self.run_model(bdfname, f06name, op2name, f06_has_weight=False)
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/test/f06_unit_tests.py", line 50, in run_model
    f06.write_f06(f06_name[:-4] + '.test_f06.out')
  File "/home/nils/svn/pynastran-read-only/pyNastran/f06/f06Writer.py", line 938, in write_f06
    for subtitle in self.subtitles[isubcase]:
AttributeError: 'F06' object has no attribute 'subtitles'

----------------------------------------------------------------------
Ran 18 tests in 2.464s

FAILED (errors=12)

**Comment by SteveDoyle2** [comment]
I'll take of this issue today and push it to the master and v0.7 branches.

**Comment by SteveDoyle2** [comment]
The bug is fixed; closing...

v0.7dev version pushed
Master pushed
