### ISSUE TITLE
ImportError: No module named op2_f06_common

### ISSUE THREAD

**Issue by nilswagner** [SteveDoyle2/pyNastran#183]
python all_tests.py 
Traceback (most recent call last):
  File "all_tests.py", line 1, in <module>
    from pyNastran.op2.test.op2_unit_tests import TestOP2
  File "/home/wagner/local/lib/python2.7/site-packages/pyNastran-0.7.0_dev-py2.7.egg/pyNastran/op2/test/op2_unit_tests.py", line 7, in <module>
    from pyNastran.op2.op2 import OP2
  File "/home/wagner/local/lib/python2.7/site-packages/pyNastran-0.7.0_dev-py2.7.egg/pyNastran/op2/op2.py", line 20, in <module>
    from pyNastran.op2.tables.lama_eigenvalues.lama import LAMA
  File "/home/wagner/local/lib/python2.7/site-packages/pyNastran-0.7.0_dev-py2.7.egg/pyNastran/op2/tables/lama_eigenvalues/lama.py", line 4, in <module>
    from pyNastran.op2.op2_common import OP2Common
  File "/home/wagner/local/lib/python2.7/site-packages/pyNastran-0.7.0_dev-py2.7.egg/pyNastran/op2/op2_common.py", line 11, in <module>
    from pyNastran.f06.f06Writer import F06Writer
  File "/home/wagner/local/lib/python2.7/site-packages/pyNastran-0.7.0_dev-py2.7.egg/pyNastran/f06/f06Writer.py", line 12, in <module>
    from pyNastran.op2.op2_f06_common import OP2_F06_Common
ImportError: No module named op2_f06_common

**Comment by SteveDoyle2** [comment]
You're in the master branch.  The bug is fixed in v0.7, but hasn't been pushed.

**Comment by SteveDoyle2** [comment]
It's now been pushed.  Imports should be a lot smoother now.
