### ISSUE TITLE
OP2 reading issues: table not implemented

### ISSUE THREAD

**Issue by watkinrt** [SteveDoyle2/pyNastran#267]
I have been unable to get pyNastran (v0.7.2) to open an OP2 file from an NX-based simulation. The traceback I get is as follows:

```
INFO:      fname=op2.py                    lineNo=107    vectorized=True combine=True
INFO:      fname=op2.py                    lineNo=111    -------- reading op2 with read_mode=1 --------
DEBUG:     fname=op2_scalar.py             lineNo=482    op2_filename = '<filename>.op2'
INFO:      fname=op2_scalar.py             lineNo=595      table_name='IBULK'
Traceback (most recent call last):

  File "<ipython-input-5-b966767a7ef9>", line 1, in <module>
    runfile('<path>/processing.py', wdir='<path>')

  File "<path>\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "<path>\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "<path>/processing.py", line 20, in <module>
    model.read_op2('20151231b_assyfem1_sim1-mac.op2')

  File "<path>\pyNastran\op2\op2.py", line 116, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)

  File "<path>\pyNastran\op2\op2_scalar.py", line 537, in read_op2
    table_names = self._read_tables(table_name)

  File "<path>\pyNastran\op2\op2_scalar.py", line 703, in _read_tables
    raise NotImplementedError('%r' % table_name)

NotImplementedError: 'IBULK'
```

In looking at op2_scalar.py, it seems that the ibulk table has yet to be implemented. I poked around and found that ibulk has been added to the developement branch v0.8; however, I still get an error when I try to read my OP2 file:

```
DEBUG:     fname=op2.py                    lineNo=340    combine=True
DEBUG:     fname=op2.py                    lineNo=341    -------- reading op2 with read_mode=1 --------
INFO:      fname=op2_scalar.py             lineNo=1022   op2_filename = '<filename>.op2'
DEBUG:     fname=op2_scalar.py             lineNo=1207     table_name='IBULK'
strings = ('BULKDATA\xff\xff\xff\xff',)
ints    = (1263293762, 1096040772, -1)
floats  = (13391170.0, 13.265933990478516, nan)
Traceback (most recent call last):

  File "<ipython-input-6-b966767a7ef9>", line 1, in <module>
    runfile('<path>/processing.py')

  File "<path>\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "<path>\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/rtwatkin/Documents/SWOT/Advanced Microwave Radiometer (AMR)/Piece Part Analysis/ReceiverChassis/Analysis/20151215A/Analysis/processing.py", line 20, in <module>
    model.read_op2('20151231b_assyfem1_sim1-mac.op2')

  File "<path>\Documents\Code\pyNastran\pyNastran\op2\op2.py", line 346, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)

  File "<path>\Documents\Code\pyNastran\pyNastran\op2\op2_scalar.py", line 1143, in read_op2
    table_names = self._read_tables(table_name)

  File "<path>\Documents\Code\pyNastran\pyNastran\op2\op2_scalar.py", line 1244, in _read_tables
    self._read_results_table()

  File "<path>\Documents\Code\pyNastran\pyNastran\op2\op2_scalar.py", line 2311, in _read_results_table
    raise NotImplementedError(msg)

NotImplementedError: len(data) = 12
strings  = 'BULKDATA\xff\xff\xff\xff'
ints     = '(1263293762, 1096040772, -1)'
floats   = '(13391170.0, 13.265933990478516, nan)'
```

So, it doesn't appear that the ibulk table read isn't fully implemented. Would this be easy to fix? Unfortunately, I don't understand the processing flow enough to know where to beginning trying the fix the problem.

If needed, I can come up with a small op2 to post as an example.

Thanks.

**Comment by SteveDoyle2** [comment]
IBULK is probably not too difficult to add (correctly).  An example problem with the BDF and OP2 would help.

Also,out of the ~5000 example problems that pyNastran is tested against, very few have the IBULK table.  I agree it should work, but do you really need or can you just remove it from your deck?

**Comment by watkinrt** [comment]
Attached are the .dat and .op2 files for a simple plate bending simulation.

> I agree it should work, but do you really need or can you just remove it from your deck?

I am currently running NX Advanced Simulation, which sets "PARAM,OIBULK,ON" by default and doesn't have an explicit way to turn it of. I can get around this by telling Adv Sim not to exported the "PARAM CARDS" block (see attached .dat) and then rewrite all of the params that I still want to use (such as unitsys, etc), but it would be nice if I didn't have to do this.

[Example.zip](https://github.com/SteveDoyle2/pyNastran/files/113066/Example.zip)

**Comment by SteveDoyle2** [comment]
That's a fairly odd table.  It's a perfect copy of the bulk data section other than the ENDDATA isn't included.  It seems like a waste of space, but that's Nastran for you.  It's now skipped properly in the master.

**Comment by watkinrt** [comment]
Your modifications did the trick! Thank you for the extremely quick turnaround time; I really appreciate it.

**Comment by SteveDoyle2** [comment]
Nice!

It was a pretty easy table.
