### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute 'removeOldGeometry'

### ISSUE THREAD

**Issue by nilswagner** [SteveDoyle2/pyNastran#291]
load_stl_geometry...
Traceback (most recent call last):
  File "/home/nils/local/bin/pyNastranGUI", line 9, in <module>
    load_entry_point('pyNastran', 'console_scripts', 'pyNastranGUI')()
  File "/home/nils/git/pynastran/pyNastran/gui/gui.py", line 272, in main
    window = MainWindow(inputs)
  File "/home/nils/git/pynastran/pyNastran/gui/gui.py", line 137, in __init__
    self.setup_post(inputs)
  File "/home/nils/git/pynastran/pyNastran/gui/gui_common.py", line 1853, in setup_post
    self.load_batch_inputs(inputs)
  File "/home/nils/git/pynastran/pyNastran/gui/gui_common.py", line 286, in load_batch_inputs
    infile_name=input_filename, name=name, geometry_format=form, plot=plot)
  File "/home/nils/git/pynastran/pyNastran/gui/gui_common.py", line 1564, in on_load_geometry
    has_results = load_function(infile_name, self.last_dir, name=name, plot=plot)
  File "/home/nils/git/pynastran/pyNastran/converters/stl/stl_io.py", line 25, in load_stl_geometry
    skip_reading = self.removeOldGeometry(stl_filename)
AttributeError: 'MainWindow' object has no attribute 'removeOldGeometry'

**Comment by SteveDoyle2** [comment]
fixed
