### ISSUE TITLE
Error get_Matrix from punch

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#326]
I've read a punch file containing NASTRAN DMIG matrices obtained via `PARAM   EXTOUT  DMIGPCH`
I get an error when using the command:

```
VAX_dmig = bdf.dmigs['VAX'];

VAXMAT = VAX_dmig .get_matrix();
```

The error is the following (same error is obtained by invoking `.getMatrix`):

```
Traceback (most recent call last):

  File "<ipython-input-11-3966519d92d4>", line 1, in <module>
    vv.get_matrix()

  File "C:\Users\10758\AppData\Local\Continuum\Anaconda3\lib\site-packages\pynastran-0.8.0+dev.no.checksum.error-py3.5.egg\pyNastran\bdf\cards\dmig.py", line 240, in get_matrix
    return get_matrix(self, is_sparse=is_sparse, apply_symmetry=apply_symmetry)

  File "C:\Users\10758\AppData\Local\Continuum\Anaconda3\lib\site-packages\pynastran-0.8.0+dev.no.checksum.error-py3.5.egg\pyNastran\bdf\cards\dmig.py", line 641, in get_matrix
    raise KeyError(msg)

KeyError: 'name=VAX ndim=2 gci=[101   1] gcj=[1 0] matrix_type=rectangular is_polar=False is_sparse=False ncols=1 M.shape=(15, 15)\nRows:\n  i=0 row=(109, 1)\n  i=1 row=(108, 1)\n  i=2 row=(105, 1)\n  i=3 row=(301, 1)\n  i=4 row=(309, 1)\n  i=5 row=(102, 1)\n  i=6 row=(308, 1)\n  i=7 row=(305, 1)\n  i=8 row=(302, 1)\n  i=9 row=(107, 1)\n  i=10 row=(106, 1)\n  i=11 row=(101, 1)\n  i=12 row=(307, 1)\n  i=13 row=(306, 1)\n  i=14 row=(201, 1)\n'
```

**Comment by SteveDoyle2** [comment]
It's trying to find the `(101, 1)` and the `(1, 0)` entry in your matrix.  I assume it's failing on the second one, but I'd need to see an example to understand it.

**Comment by alby3z** [comment]
Attached the test punch file:

**Comment by SteveDoyle2** [comment]
the bug is fixed now

**Comment by SteveDoyle2** [comment]
closing due to innactivity & because I think it's fixed
