### ISSUE TITLE
OP2 reader Error : NotImplementedError: eigenvectors; table_name=OUG1

### ISSUE THREAD

**Issue by b1a2b3c4d** [SteveDoyle2/pyNastran#392]
Traceback (most recent call last):
  File "C:\Users\pyNastran\gui\gui_common.py", line 3486, in on_load_results
    load_function(out_filenamei, self.last_dir)
  File "C:\Users\pyNastran\converters\nastran\nastranIOv.py", line 3726, in load_nastran_results
    model.read_op2(op2_filename, combine=False)
  File "C:\Users\pyNastran\op2\op2.py", line 394, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)
  File "C:\User\pyNastran\op2\op2_interface\op2_scalar.py", line 1299, in read_op2
    table_names = self._read_tables(table_name)
  File "C:\User\pyNastran\op2\op2_interface\op2_scalar.py", line 1410, in _read_tables
    self._read_results_table()
  File "C:\Users\pyNastran\op2\op2_interface\op2_scalar.py", line 1866, in _read_results_table
    self._read_subtables()
  File "C:\Users\pyNastran\op2\fortran_format.py", line 390, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "C:\Users\pyNastran\op2\fortran_format.py", line 462, in _read_subtable_3_4
    n = self._read_subtable_results(table4_parser, record_len)
  File "C:\Users\pyNastran\op2\fortran_format.py", line 588, in _read_subtable_results
    n = table4_parser(data, ndata)
  File "C:\Users\pyNastran\op2\tables\oug\oug.py", line 318, in _read_oug_4
    n = self._read_oug_eigenvector(data, ndata)
  File "C:\Users\pyNastran\op2\tables\oug\oug.py", line 619, in _read_oug_eigenvector
    raise NotImplementedError(msg)
NotImplementedError: eigenvectors; table_name=OUG1

[the op2 file is here](https://drive.google.com/open?id=0BxaMFoAUrxpBUGJMR19ud0NCeVk)

**Comment by SteveDoyle2** [comment]
Thanks for the model.

The OUG1 table is now supported for eigenvectors.
