### ISSUE TITLE
Problem while cross referencing

### ISSUE THREAD

**Issue by ToniThiele** [SteveDoyle2/pyNastran#410]
Dear Steve,
at first....thank you for this package.

I've a smal problem with cross referencing (whatever this may).

I will only show the result of op2-file and uns this small script:
`from pyNastran.op2.op2_geom import OP2Geom, read_op2_geom `
`model = read_op2_geom('BMW.op2') `

The result i've get is this:

DEBUG:   op2.py:409                   finished reading op2
DEBUG:   cross_reference.py:148       Cross Referencing...

Traceback (most recent call last):
  File "C:/Users/tthiele/Download_TT/pyNastran/readOP2.py", line 2, in <module>
    model = read_op2_geom('BMW.op2')
  File "C:\Users\tthiele\AppData\Local\Continuum\Miniconda2\lib\site-packages\pyNastran\op2\op2_geom.py", line 82, in read_op2_geom
    model.cross_reference()
  File "C:\Users\tthiele\AppData\Local\Continuum\Miniconda2\lib\site-packages\pyNastran\bdf\bdf_interface\cross_reference.py", line 165, in cross_reference
    self._cross_reference_constraints()
  File "C:\Users\tthiele\AppData\Local\Continuum\Miniconda2\lib\site-packages\pyNastran\bdf\bdf_interface\cross_reference.py", line 183, in _cross_reference_constraints
    spc.cross_reference(self)
  File "C:\Users\tthiele\AppData\Local\Continuum\Miniconda2\lib\site-packages\pyNastran\bdf\cards\constraints.py", line 1257, in cross_reference
    self.sets[i] = model.SPC(spc, msg=msg)
  File "C:\Users\tthiele\AppData\Local\Continuum\Miniconda2\lib\site-packages\pyNastran\bdf\bdf_interface\get_methods.py", line 253, in SPC
    spc_id, msg, np.unique(list(self.spcs.keys()))))
KeyError: u'cannot find SPC ID=-1, which is required by SPCADD=101.\nAllowed SPCs=[ 101 1200 1201 1203 1205 1207 1209]' 

Can you help me whats the problem?

Best regards,
Toni

**Comment by SteveDoyle2** [comment]
I recommend going through the documentation that's linked off the top of the main page for a discussion on cross referencing.  It makes accessing objects significantly easier.

What you're running into with the -1 value is a bug, so I'd need to see an example.  

The OP2Geom class is basically reading the geometry and results, while the OP2 class reads just the results.  You can just read the BDF separately to get all the data that you get with the OP2Geom class.  There are some limitations that the OP2 format has regarding dropping important information (e.g., case control, aero cards), but it's nice because it's faster.

**Comment by SteveDoyle2** [comment]
Did you have an example?

**Comment by ToniThiele** [comment]
Sorry Steve because my late response.  
I have only one file which I want to open.  
But I can't send it because it's confidential. 
Nevertheless thanks to you. 
Best regards, 
Toni Thiele


Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: SteveDoyle2 <notifications@github.com> 
Datum: 31.08.2017  18:18  (GMT+01:00) 
An: SteveDoyle2/pyNastran <pyNastran@noreply.github.com> 
Cc: ToniThiele <toni.thiele@posteo.de>,Author <author@noreply.github.com> 
Betreff: Re: [SteveDoyle2/pyNastran] Problem while cross referencing (#410) 
 
Did you have an example?

**Comment by SteveDoyle2** [comment]
closing due to no example
