### ISSUE TITLE
error reading OEFITSTN table in op2 file

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#445]
Here's the traceback and debug info... I'm not able to provide you the op2 unfortunately.  I have **skip_undefined_matrices=True** defined, but it still fails.  This is using 1.1-dev

DEBUG:   op2.py:434                   combine=True
DEBUG:   op2.py:435                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1305           op2_filename = 'filename.op2'
DEBUG:   op2_scalar.py:1531             table_name=b'OQG1'
DEBUG:   op2_scalar.py:1531             table_name=b'OQMG1'
DEBUG:   op2_scalar.py:1531             table_name=b'OUG1'
DEBUG:   op2_scalar.py:1531             table_name=b'OES1C'
DEBUG:   op2_scalar.py:1531             table_name=b'OEFIT'
DEBUG:   op2_scalar.py:1531             table_name=b'OSTR1C'
DEBUG:   op2_scalar.py:1531             table_name=b'OEFITSTN'
WARNING: minor_tables.py:1372         unexpected tout for b'OEFITSTN': matrix_num=102 form=0 mrows=1 ncols=554 tout=0 nvalues=0 g=0
Traceback (most recent call last):
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\tables\minor_tables.py", line 943, in _read_matrix
    self._read_matrix_mat()
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\tables\minor_tables.py", line 1373, in _read_matrix_mat
    raise RuntimeError(msg)
RuntimeError: unexpected tout for b'OEFITSTN': matrix_num=102 form=0 mrows=1 ncols=554 tout=0 nvalues=0 g=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:/redmond/MRedAero-mrnastran/pynastran_h5.py", line 8, in <module>
    op2.read_op2(op2_file, skip_undefined_matrices=True)
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\op2.py", line 440, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=op2_filename)
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1362, in read_op2
    table_names = self._read_tables(table_name)
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1576, in _read_tables
    self._read_matrix(table_name)
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\tables\minor_tables.py", line 948, in _read_matrix
    self._read_matpool_matrix()
  File "C:\Users\ra054112\Desktop\WinPython-64bit-3.5.2.1Qt5\python-3.5.2.amd64\lib\site-packages\pyNastran\op2\tables\minor_tables.py", line 990, in _read_matpool_matrix
    assert header[:3] == (114, 1, 120), 'header[:3]=%s header=%s' % (header[:3], header)
AssertionError: header[:3]=(12, 25, 95) header=(12, 25, 95, b'\x1cL\x14\x00\x1cL\x14\x00', 0, 0, 11330204, 1, 9, 14, 0)

**Comment by mjredmond** [comment]
Correct, it is MSC Nastran 2010.  I didn't realize the option was skip_undefined_MATRICES, I completely glanced over that part.  It seems to be skipping it fine now.  Thanks!
