### ISSUE TITLE
bdf mirror on CAERO1 with AEFACT

### ISSUE THREAD

**Issue by a-deblois** [SteveDoyle2/pyNastran#563]
Hello,

I would like to mirror a model that contains CAERO1 with some AEFACT in the chord direction, i.e LCHORD !=0. At the moment, pyNastran asserts that (assert caero.lchord == 0). We could simply use the same ID of the AEFACT for the mirrored panel...
Thanks for your support,
Antoine

**Comment by SteveDoyle2** [comment]
Do you have an example?

**Comment by a-deblois** [comment]
Hello,
here is a stripped out example. I ran the following command, using pyNastran-1.2
bdf mirror --plane xz -o DLM_model_example_mirror.dat DLM_model_example.dat
Thanks
[DLM_model_example.zip](https://github.com/SteveDoyle2/pyNastran/files/3357403/DLM_model_example.zip)

**Comment by SteveDoyle2** [comment]
Give it a shot.  I think it's right.

I also found an issue with xy plane mirroring.  Doesn't matter for your problem, but still an issue.

**Comment by a-deblois** [comment]
Tks for that.
So the assert on the lchord seems ok, though I get a new assert issue!
Traceback (most recent call last):
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/bin/bdf", line 11, in <module>
    load_entry_point('pyNastran==1.3.0+dev.no.checksum.error', 'console_scripts', 'bdf')()
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/mesh_utils/utils.py", line 1060, in cmd_line
    cmd_line_mirror(argv, quiet=quiet)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/mesh_utils/utils.py", line 371, in cmd_line_mirror
    plane=plane, log=log)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/mesh_utils/mirror_mesh.py", line 145, in write_bdf_symmetric
    model, nid_offset, eid_offset = bdf_mirror(bdf_filename, plane=plane, log=None)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/mesh_utils/mirror_mesh.py", line 82, in bdf_mirror
    eid_offset = _mirror_elements(model, mirror_model, nid_offset)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/mesh_utils/mirror_mesh.py", line 428, in _mirror_elements
    alpha=rigid_element.alpha, comment='')
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/bdf_interface/add_card.py", line 6245, in add_rbar
    self._add_rigid_element_object(elem)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/envs/py37/lib/python3.7/site-packages/pyNastran-1.3.0+dev.no.checksum.error-py3.7.egg/pyNastran/bdf/bdf_interface/add_methods.py", line 313, in _add_rigid_element_object
    assert elem.eid not in self.rigid_elements, 'eid=%s\noldElement=\n%snewElement=\n%s' % (elem.eid, self.rigid_elements[elem.eid], elem)
AssertionError: eid=5004042
oldElement=
RBAR     5004042 5000013 5000042  123456                  123456
newElement=
RBAR     50040421800108118001109  123456                  123456

Is it possible that the algo to assign a new ID would be the culprit?
I'll try to give another test case, though more difficult to make a smaller one that still reproduces the issue

**Comment by SteveDoyle2** [comment]
That's weird.  There's a test for the RBAR.  The code looks fine...

The algorithm is just:
eid_offset = max(eid_max_elements, eid_max_masses, eid_max_rigid)
eid_mirror = eid + eid_offset

I think I need an example.

**Comment by a-deblois** [comment]
Here is an example (all grids and properties are random, but still reproduces the error).
cheers
[DLM_model_example2.zip](https://github.com/SteveDoyle2/pyNastran/files/3364069/DLM_model_example2.zip)

**Comment by SteveDoyle2** [comment]
Looks like the eid_offset was accidentally defined twice (the 2nd time being just `eid_offset=eid_max_elements`).  It's fixed now.

I also mirrored the PLOTELs.
