### ISSUE TITLE
OP2-Import Error

### ISSUE THREAD

**Issue by BaurAndreas** [SteveDoyle2/pyNastran#575]
Hello Steve,

first of all I want to say thank you for the great work you did with pyNastran. 

I'm using pyNastran for automated op2-import and automated post processing. The company I'm working for uses Siemens NX Nastran 12. 

Since the company has changed from NX10 to NX12 I get the following error, if I try to import an op2-file:

  ```
File "<ipython-input-3-e00ee8fbc586>", line 1, in <module>
    op2.read_op2(os.path.join(work_dir,op2_file))#,build_dataframe=True)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2.py", line 585, in read_op2
    load_as_h5=load_as_h5)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1355, in read_op2
    table_names = self._read_tables(table_name)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1506, in _read_tables
    raise NotImplementedError(msg)

NotImplementedError: Invalid Table = b'ICASE'

If you have matrices that you want to read, see:
  model.set_additional_matrices_to_read(matrices)  matrices = {
      b'BHH' : True,
      b'KHH' : False,
  }  # you want to read some matrices, but not others
  matrices = [b'BHH', b'KHH']  # assumes True

If you the table is a geom/result table, see:
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OUGV1' : [method3, method4],
      b'GEOM4SX' : [method3, method4],
      b'OES1X1' : False,
  }

If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
  methods_dict = {
      b'OUGV1' : [method],
  }
  model.set_additional_generalized_tables_to_read(methods_dict)
```

Excluding the 'ICASE' table by the following code

```
methods_dict = {b'ICASE':False}
op2.set_additional_result_tables_to_read(methods_dict)
```

leads to the following error:

```
ndata = 24:
  strings = (b'CASE CONTROL SECTION\xff\xff\xff\xff',)
  ints    = (1163084099, 1313817376, 1280266836, 1128616736, 1313818964, -1)
  floats  = (3380.078857421875, 869320704.0, 54348112.0, 197.32470703125, 869422336.0, nan)

Traceback (most recent call last):

  File "<ipython-input-4-016068208e15>", line 5, in <module>
    op2.read_op2(os.path.join(work_dir,op2_file))#,build_dataframe=True)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2.py", line 585, in read_op2
    load_as_h5=load_as_h5)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1355, in read_op2
    table_names = self._read_tables(table_name)

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1474, in _read_tables
    op2_reader.read_results_table()

  File "C:\Users\baura\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.6.egg\pyNastran\op2\op2_interface\op2_reader.py", line 2879, in read_results_table
    raise NotImplementedError(msg)

NotImplementedError: len(data) = 24
strings  = b'CASE CONTROL SECTION\xff\xff\xff\xff'
ints     = '(1163084099, 1313817376, 1280266836, 1128616736, 1313818964, -1)'
floats   = '(3380.078857421875, 869320704.0, 54348112.0, 197.32470703125, 869422336.0, nan)
```
I attached my .op2-file that doesn't work. It is just a simple bending beam. 

Could you help me, please?

Regards
Andreas

[model.zip](https://github.com/SteveDoyle2/pyNastran/files/3711045/model.zip)

**Comment by BaurAndreas** [comment]
Oh, okay. Thank you for answering so fast.
