### ISSUE TITLE
Trouble reading op2 file with random vibe results

### ISSUE THREAD

**Issue by derrickearly** [SteveDoyle2/pyNastran#582]
I'm having trouble reading the attached op2 file.  The compressed file size is 754MB, so I cannot attach a copy.

I get the following error message:

runfile('C:/Users/daearly/Documents/My Laptop/Goes/LM Spacecraft/FEM/2019 spacex random/fdlc_updated/read_op2_write_h5.py', wdir='C:/Users/daearly/Documents/My Laptop/Goes/LM Spacecraft/FEM/2019 spacex random/fdlc_updated')
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
Traceback (most recent call last):

  File "<ipython-input-3-d3b3f3720741>", line 1, in <module>
    runfile('C:/Users/daearly/Documents/My Laptop/Goes/LM Spacecraft/FEM/2019 spacex random/fdlc_updated/read_op2_write_h5.py', wdir='C:/Users/daearly/Documents/My Laptop/Goes/LM Spacecraft/FEM/2019 spacex random/fdlc_updated')

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/daearly/Documents/My Laptop/Goes/LM Spacecraft/FEM/2019 spacex random/fdlc_updated/read_op2_write_h5.py", line 19, in <module>
    model.read_op2(op2_filename)

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\pyNastran\op2\op2.py", line 632, in read_op2
    load_as_h5=load_as_h5, mode=mode)

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1485, in read_op2
    table_names = self._read_tables(table_name)

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1632, in _read_tables
    op2_reader.mapped_tables[table_name]()

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py", line 978, in read_frl
    assert idata[1] == 1, idata

AssertionError: (101, 3, 0, 0, 0, 0, 0)

**Comment by SteveDoyle2** [comment]
Can you make a smaller model?  I can't debug it without an example.

**Comment by derrickearly** [comment]
I'll try reducing the output size.  It will take some time.  If you provide your email, I could send you the file via a large file transfer site.  My work email is derrick.a.early@nasa.gov

**Comment by derrickearly** [comment]
I found a work around by writing the matrices that I needed using nastran's output4 format via a dmap alter.  I used your op4 reader to convert the matrices into matlab format.  I really appreciate your pyNastran tools!

**Comment by SteveDoyle2** [comment]
Good!  I'm glad!  It's tough to get random analysis perfect when I do very little of it :)

v1.3 should have this fix and PSDF table reading support (so you get the entire PSD).

**Comment by derrickearly** [comment]
Thank you!
