### ISSUE TITLE
pyNastran generates errors wile reading Nastran95 OP2 files

### ISSUE THREAD

**Issue by mcmullen-ms** [SteveDoyle2/pyNastran#603]
I'm writing an OP2 file using an ALTER statement in the Executive Control section of the current release of NASTRAN95...

ID XXXXX,NASTRAN                                                                  
APP DISPLACEMENT                                                                
SOL 1,0                                                                         
ALTER      110
OUTPUT2    OUGV1,OEF1,OES1,,//-1/12////*MSC*  $
OUTPUT2    ,,,,, //-9/12/  $
ENDALTER  
CEND                                                                            

I'm then trying to read this OP2 file into the pyNastranGUI (version 1.2.1 on Mac OS 10.15.3) but receive the following error ...

(base) pa-lt-e27e:test3 $ pyNastranGUI
qt_version = 'pyqt5'
supported_formats = [u'nastran', u'nastran', u'abaqus', u'avus', u'bedge', u'surf', u'ugrid', u'ugrid3d', u'cart3d', u'degen_geom', u'fast', u'lawgs', u'obj', u'openfoam_hex', u'openfoam_shell', u'openfoam_faces', u'panair', u'shabp', u'stl', u'su2', u'tecplot', u'tetgen', u'usm3d', u'avl']
load_batch_inputs {'user_geom': None, 'format': None, 'postscript': None, 'user_points': None, 'output': None, 'geomscript': None, 'log': None, 'debug': True, 'is_groups': False, 'test': False, 'input': None}
pyNastran 1.3.2 is now availible; current=1.2.1
is_failed = False
name = 'main'
    nid=2048 is a dependent node and has a FORCE applied
FORCE          1    2048              1.      0.      0. 179.795

    nid=1391 is a dependent node and has a FORCE applied
FORCE          1    1391              1.      0.      0. 87.8689

dt_load = 4.98 sec = 0.08 min
need to add u'_create_nastran_tools_and_menu_items'
trying to read.../Users/xxxxx/NASTRAN-95/test3/test1.op2
--Table3Data--

  device_code   = 1   Print
  analysis_code = 1   Statics
  table_code    = 4   OEF1-OEF - Element Force
  format_code   = 1   Real
  sort_method   = 1
  sort_code     = 0
    sort_bits   = (0, 0, 0)
    data_format = 0   Real
    sort_type   = 0   Sort1
    is_random   = 0   Sorted Responses
  random_code   = 0  
  element_type  = 64  CQUAD8
  thermal       = 0   isHeatTransfer = False
  thermal_bits  = [0, 0, 0, 0, 0]
  num_wide      = 9  
  isubcase      = 1  
  MSC Nastran

failed reading OES1 isubtable=-4
Traceback (most recent call last):
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/gui/qt_files/load_actions.py", line 287, in on_load_results
    load_function(out_filenamei)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/converters/nastran/nastran_io.py", line 5885, in load_nastran_results
    model.read_op2(op2_filename, combine=False)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2.py", line 632, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1485, in read_op2
    table_names = self._read_tables(table_name)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1639, in _read_tables
    op2_reader.read_results_table()
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3305, in read_results_table
    self._read_subtables()
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3400, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3505, in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/fortran_format.py", line 104, in _read_subtable_results
    n = table4_parser(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 295, in _read_oes1_4
    n = self._read_oes_4_sort(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 535, in _read_oes_4_sort
    n = self._read_oes1_loads(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 1296, in _read_oes1_loads
    n, nelements, ntotal = self._oes_cquad4_144(data, ndata, dt, is_magnitude_phase, stress_name, prefix, postfix)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 4267, in _oes_cquad4_144
    raise RuntimeError(self.code_information())
RuntimeError: --Table3Data--

  device_code   = 1   Print
  analysis_code = 1   Statics
  table_code    = 5   OES1-OES - Element Stress
  format_code   = 1   Real
  sort_method   = 1
  sort_code     = 0
    sort_bits   = (0, 0, 0)
    data_format = 0   Real
    sort_type   = 0   Sort1
    is_random   = 0   Sorted Responses
  random_code   = 0  
  element_type  = 64  CQUAD8
  s_code        = 0   Coordinate Element - Stress Max Shear (Octahedral)
  thermal       = 0   isHeatTransfer = False
  thermal_bits  = [0, 0, 0, 0, 0]
  num_wide      = 17 
  isubcase      = 1  
  lsdvmn        = 1
  MSC Nastran

Traceback (most recent call last):
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/gui/qt_files/gui_attributes.py", line 276, in new_func
    n = func(self, *args, **kwargs)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/gui/qt_files/gui_attributes.py", line 1027, in on_load_results
    self.load_actions.on_load_results(out_filename=out_filename)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/gui/qt_files/load_actions.py", line 287, in on_load_results
    load_function(out_filenamei)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/converters/nastran/nastran_io.py", line 5885, in load_nastran_results
    model.read_op2(op2_filename, combine=False)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2.py", line 632, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1485, in read_op2
    table_names = self._read_tables(table_name)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1639, in _read_tables
    op2_reader.read_results_table()
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3305, in read_results_table
    self._read_subtables()
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3400, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3505, in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/fortran_format.py", line 104, in _read_subtable_results
    n = table4_parser(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 295, in _read_oes1_4
    n = self._read_oes_4_sort(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 535, in _read_oes_4_sort
    n = self._read_oes1_loads(data, ndata)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 1296, in _read_oes1_loads
    n, nelements, ntotal = self._oes_cquad4_144(data, ndata, dt, is_magnitude_phase, stress_name, prefix, postfix)
  File "/Users/xxxxx/opt/miniconda2/lib/python2.7/site-packages/pyNastran/op2/tables/oes_stressStrain/oes.py", line 4267, in _oes_cquad4_144
    raise RuntimeError(self.code_information())
RuntimeError: --Table3Data--

  device_code   = 1   Print
  analysis_code = 1   Statics
  table_code    = 5   OES1-OES - Element Stress
  format_code   = 1   Real
  sort_method   = 1
  sort_code     = 0
    sort_bits   = (0, 0, 0)
    data_format = 0   Real
    sort_type   = 0   Sort1
    is_random   = 0   Sorted Responses
  random_code   = 0  
  element_type  = 64  CQUAD8
  s_code        = 0   Coordinate Element - Stress Max Shear (Octahedral)
  thermal       = 0   isHeatTransfer = False
  thermal_bits  = [0, 0, 0, 0, 0]
  num_wide      = 17 
  isubcase      = 1  
  lsdvmn        = 1
  MSC Nastran

The BDF file contains only CQUAD4 and CTRIA3 elements.

Have I done something wrong with my Nastran95 DMAP Alter (I'm only asking because Steve Doyle is also listed as the owner of the GitHub Nastran95 repo) or is there a bug in the pyNastran OP2 reader?

Thanks for the help,
Matt

**Comment by SteveDoyle2** [comment]
So NASTRAN-95 is not supported at all in pyNastran 1.2.1.  

A small subset of it is supported in 1.3, but it looks like the CQUAD4 is not.  As to why it's mentioning a CQUAD8, it identified your deck as MSC Nastran.  For that, element type 64 is a CQUAD8.  It's a CQUAD4 in NASTRAN-95.  As to how to set the version, in the bdf, add:
    $ pynastran: version=nasa95

Can you attach the bdf and op2?

**Comment by mcmullen-ms** [comment]
I was unaware that Nastran95 supported CQUAD8 elements, as I can find no reference to this element type anywhere in the code or documentation.  If this is true, and the CQUAD4 element is not supported in pyNastran version 1.3, then I'm going to have to identify an alternative process. 

I'm not completely aware of the development history of Nastran, but it seems that the OP2 format was popularized by MSC well after Nastran95 was frozen. Do you know the Nastran95 Alter sequence to provide the standard OP2 file? I've seen your support comments on the Nastran95 site, and these are the basis for the Alter sequence provided above. I have used these exact sequences to generate OP2 files that were input into other software (other than pyNastran) - yet they still generated errors on reading that indicated that there is missing geometry (nodes and elements) information (should I be included the GEOM1 or GEOM2 tables). I can't seem to find an MSC programmers manual that will answer this question. I understand that this is probably outside of your responsibilities relative to your maintenance of pyNastran, but any help would be appreciated.

The BDF and OP2 files can't be publicly distributed. If we can identify a path forward with pyNastran, I'll provide you with a surrogate for testing purposes.

Thanks for the help,
Matt

**Comment by SteveDoyle2** [comment]
> I was unaware that Nastran95 supported CQUAD8 elements, 

It is not a CQUAD8.  That is an incorrect message because the code think you are using MSC Nastran.  It is not difficult to support it, but I don't support elements that I haven't seen.

> Do you know the Nastran95 Alter sequence to provide the standard OP2 file?

No.  I'm not good at DMAP.  I would be surprised if there is an easy one.

> I have used these exact sequences to generate OP2 files that were input into other software (other than pyNastran) - yet they still generated errors on reading that indicated that there is missing geometry (nodes and elements) information (should I be included the GEOM1 or GEOM2 tables)

I'm not following.  As I said, NASTRAN-95 is not well supported.  The software is targeted towards modern Nastran.

**Comment by mcmullen-ms** [comment]
I appreciate the responses - thanks for the help.
Matt
