### ISSUE TITLE
importing BDF causes TypeError: Unsupported type type for Int

### ISSUE THREAD

**Issue by Bravo-Kilo** [SteveDoyle2/pyNastran#606]
fresh new install, no errors on install
tried python versions 3.6, 3.7, 3.8

the import (taken straight from tutorial/example) 
from pyNastran.bdf.bdf import BDF 

The error:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\typish\classes\_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\functions\_get_type.py", line 65, in _get_type_type
    return delegate(type_)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\functions\_get_type.py", line 126, in get_type_int
    return _get_type_of_number(Int, obj, {
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\functions\_get_type.py", line 97, in _get_type_of_number
    raise TypeError('Unsupported type {} for {}'
TypeError: Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\typish\classes\_cls_function.py", line 68, in __call__
    return callable_(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\types\_ndarray_meta.py", line 156, in _sizes_and_type
    cls._only_type(item[1])
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\types\_ndarray_meta.py", line 134, in _only_type
    cls._type = Any if item is Any else get_type(item)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\functions\_get_type.py", line 45, in get_type
    return function(obj)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\typish\classes\_cls_function.py", line 70, in __call__
    raise TypeError('Unable to call function for \'{}\': {}'
TypeError: Unable to call function for '<class 'bool'>': Unsupported type type for Int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\pyNastran\bdf\bdf.py", line 165, in <module>
    from .bdf_methods import BDFMethods
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\pyNastran\bdf\bdf_methods.py", line 30, in <module>
    from pyNastran.nptyping import NDArray3float
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\pyNastran\nptyping.py", line 16, in <module>
    NDArrayNbool = NDArray[(Any, ), bool]
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\typish\classes\_subscriptable_type.py", line 37, in __getitem__
    result._after_subscription(item)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\nptyping\types\_ndarray_meta.py", line 121, in _after_subscription
    method(item)
  File "C:\ProgramData\Miniconda3\envs\py38\lib\site-packages\typish\classes\_cls_function.py", line 70, in __call__
    raise TypeError('Unable to call function for \'{}\': {}'
TypeError: Unable to call function for '((typing.Any,), <class 'bool'>)': Unable to call function for '<class 'bool'>': Unsupported type type for Int

**Comment by SteveDoyle2** [comment]
The software doesn't work in Python 3.6.

It looks like your issue is your version of nptyping.  You need 1.0.1.  There was no `nptyping.__version__`  until 1.0, so if you don't have it, that's your issue.

**Comment by SteveDoyle2** [comment]
*at least 1.0.1

**Comment by Bravo-Kilo** [comment]
I have nptyping 1.1.0 installed

**Comment by SteveDoyle2** [comment]
Try 1.0.1

**Comment by Bravo-Kilo** [comment]
Downgrading to nptypings v 1.0.1 worked

Thank you, sir!

**Comment by zuckberj** [comment]
+1
Same issue with Python 3.8 and nptyping 1.1.0
Dowgrading to 1.0.1 works!

**Comment by SteveDoyle2** [comment]
I'm working on the next version with this and some other fixes.  It'll support nptyping 1.1.  Hopefully out this week.
