### ISSUE TITLE
op2 nastran95

### ISSUE THREAD

**Issue by PavelSchor** [SteveDoyle2/pyNastran#612]
Hello,
I'm trying to read balsa_wingbox.op2 from pyNastran/model/nasa_nastran. The op2 reader crashes with following errors:

`trying to read.../home/pavel/src/pyNastran/models/nasa_nastran/balsa_wingbox.op2

ndata = 0:
  strings = (b'',)
  ints    = ()
  floats  = ()

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4127, in _read_table_name
    data = self._read_record(macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3929, in _read_record
    return self._read_record_ndata4(debug=debug, macro_rewind=macro_rewind)[0]
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3940, in _read_record_ndata4
    markers0 = self.get_nmarkers4(1, rewind=False, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3737, in get_nmarkers4
    marker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4140, in _read_table_name
    self.read_markers([0], macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3793, in read_markers
    return self.read_markers4(markers, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3821, in read_markers4
    imarker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/gui/qt_files/load_actions.py", line 296, in on_load_results
    load_function(out_filenamei)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/converters/nastran/gui/nastran_io.py", line 5430, in load_nastran_results
    model.read_op2(op2_filename, combine=False)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2.py", line 541, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1566, in read_op2
    table_names = self._read_tables(table_name)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1768, in _read_tables
    table_name = op2_reader._read_table_name(rewind=True, stop_on_failure=False)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4147, in _read_table_name
    raise FatalError('There was a Nastran FATAL Error.  Check the F06.\n'
pyNastran.f06.errors.FatalError: There was a Nastran FATAL Error.  Check the F06.
last table=b'OES1'; post=-1 version='msc'

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4127, in _read_table_name
    data = self._read_record(macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3929, in _read_record
    return self._read_record_ndata4(debug=debug, macro_rewind=macro_rewind)[0]
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3940, in _read_record_ndata4
    markers0 = self.get_nmarkers4(1, rewind=False, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3737, in get_nmarkers4
    marker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4140, in _read_table_name
    self.read_markers([0], macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3793, in read_markers
    return self.read_markers4(markers, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3821, in read_markers4
    imarker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/gui/qt_files/gui_attributes.py", line 304, in new_func
    n = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/gui/qt_files/gui_attributes.py", line 1054, in on_load_results
    self.load_actions.on_load_results(out_filename=out_filename)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/gui/qt_files/load_actions.py", line 296, in on_load_results
    load_function(out_filenamei)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/converters/nastran/gui/nastran_io.py", line 5430, in load_nastran_results
    model.read_op2(op2_filename, combine=False)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2.py", line 541, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1566, in read_op2
    table_names = self._read_tables(table_name)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1768, in _read_tables
    table_name = op2_reader._read_table_name(rewind=True, stop_on_failure=False)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4147, in _read_table_name
    raise FatalError('There was a Nastran FATAL Error.  Check the F06.\n'
pyNastran.f06.errors.FatalError: There was a Nastran FATAL Error.  Check the F06.
last table=b'OES1'; post=-1 version='msc'
Aborted
`

Output from test_op2 is:

`~/src/pyNastran/models/nasa_nastran$ test_op2 balsa_wingbox.op2 
autodesk     = False
binarydebug  = False
disablecompare = False
exclude      = []
geometry     = False
help         = False
is_mag_phase = False
is_sort2     = False
load_hdf5    = False
nasa95       = False
nocombine    = False
nx           = False
pandas       = False
post         = None
profile      = False
quiet        = False
safe         = False
short_stats  = False
subcase      = None
version      = False
write_bdf    = False
write_f06    = False
write_hdf5   = False
write_op2    = False
write_xlsx   = False
h            = False
v            = False
OP2_FILENAME = 'balsa_wingbox.op2'
DEBUG:   test_op2.py:271              subcases = []
DEBUG:   op2_scalar.py:575            set_subcases - subcases = []
DEBUG:   op2_scalar.py:575            set_subcases - subcases = []
DEBUG:   op2.py:529                   combine=True
DEBUG:   op2.py:530                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1534           op2_filename = 'balsa_wingbox.op2'
DEBUG:   op2_reader.py:263            mode = 'msc'
DEBUG:   op2_scalar.py:1713             table_name=b'OUGV1'
DEBUG:   op2_scalar.py:1713             table_name=b'OEF1'
DEBUG:   op2_scalar.py:1713             table_name=b'OES1'

ndata = 0:
  strings = (b'',)
  ints    = ()
  floats  = ()

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4127, in _read_table_name
    data = self._read_record(macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3929, in _read_record
    return self._read_record_ndata4(debug=debug, macro_rewind=macro_rewind)[0]
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3940, in _read_record_ndata4
    markers0 = self.get_nmarkers4(1, rewind=False, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3737, in get_nmarkers4
    marker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4140, in _read_table_name
    self.read_markers([0], macro_rewind=rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3793, in read_markers
    return self.read_markers4(markers, macro_rewind=macro_rewind)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3821, in read_markers4
    imarker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/test_op2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/test/test_op2.py", line 649, in main
    post=data['--post'],
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/test/test_op2.py", line 280, in run_op2
    op2_nv.read_op2(op2_filename, combine=combine)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2.py", line 541, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1566, in read_op2
    table_names = self._read_tables(table_name)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1768, in _read_tables
    table_name = op2_reader._read_table_name(rewind=True, stop_on_failure=False)
  File "/usr/local/lib/python3.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 4147, in _read_table_name
    raise FatalError('There was a Nastran FATAL Error.  Check the F06.\n'
pyNastran.f06.errors.FatalError: There was a Nastran FATAL Error.  Check the F06.
last table=b'OES1'; post=-1 version='msc'
`

**Comment by SteveDoyle2** [comment]
pyNastran.f06.errors.FatalError: There was a Nastran FATAL Error. Check the F06.
    last table=b'OES1'; post=-1 version='msc'

It's not an MSC deck.  You have to call **read_op2** with the **mode='nasa95'** flag

**Comment by SteveDoyle2** [comment]
alternatively:

    test_op2 file.op2 --nasa95

**Comment by PavelSchor** [comment]
Hello Steve,
calling:

`model = OP2()                                                                                                                                                                           
 model.set_as_nasa95()                                                                                                                                                                   
 model.read_op2('balsa_wingbox.op2')`

works fine. However calling: 

`read_op2('balsa_wingbox.op2',mode='nasa95') `

produces the error above. This also causes the gui to crash.

**Comment by SteveDoyle2** [comment]
Oh...I didn't realize you were using the GUI.

It looks the test I had called the OP2 in a different way.  I (poorly) fixed the bug, but I should redo how it works.  The following case-insensitive line is also required in the input deck:

    $ pyNastran: version=nasa95

![image](https://user-images.githubusercontent.com/1059417/85622295-85008f00-b61b-11ea-835e-7059b933d692.png)

**Comment by PavelSchor** [comment]
As far as I know, there is paraview reader which can open op2. However is really easy to modify the pyNastranGUI to save vtp or vtm files: We just create writer, convert the unstructuredGrid into polydata and attach values from cards:

`		writer=vtk.vtkXMLPolyDataWriter()
		writer.SetFileName(fname)
		
		appendFilter=vtk.vtkAppendPolyData()
		geometryFilter=vtk.vtkGeometryFilter()
		geometryFilter.SetInputData(self.uGrid)
		geometryFilter.Update()
		upolydata = geometryFilter.GetOutput()
		upolydata.GetPointData().AddArray(self.DISPLACEMENT)
		appendFilter.AddInputData(upolydata)
		#if self.writePolydata:
			#appendFilter.AddInputData(self.output.polydata)
		
		#if self.writeObjects:
			#appendFilter.AddInputConnection(self.output.objects.GetOutputPort())
		writer.SetInputConnection(appendFilter.GetOutputPort())
		writer.Write()`
I would suggest to keep the grid and widgets(forces, constrains) in separate files.

Salome has also very limited support of nastran, but writing a script to save a valid bdf is also easy. I did it for beam elements.

**Comment by SteveDoyle2** [comment]
> I would suggest to keep the grid and widgets(forces, constrains) in separate files.

Yeah I guess I prefer not to use Paraview for viewing Nastran models.  I don't plan to make an nice way to export a model to Paraview, but am open if you (or someone else) wants to do it.  My concerns about Paraview lie in that they don't understand Nastran models, so understanding say how to do an animation with all the different actors is not something that is handled by Paraview.
