### ISSUE TITLE
read_op2 function got error when reading the OSMPF1 results data block.

### ISSUE THREAD

**Issue by hoshino23** [SteveDoyle2/pyNastran#643]
Hello Steve,

I have been using pyNastran and would like to thank you for your great work.
Now I am facing an error reading OP2, which probably contains the OSMPF1 results data block.

Version:
```
Python 3.8.2
pyNastran 1.3.3
```

Code:
```
from pyNastran.op2.op2 import OP2
op2 = OP2()
op2.read_op2("results.op2") 

```

Result:
```
DEBUG:   op2.py:542                   combine=True
DEBUG:   op2.py:543                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1556           op2_filename = 'results.op2'
WARNING: op2_reader.py:268            No mode was set, assuming 'msc'
DEBUG:   op2_reader.py:270            mode = 'msc'
DEBUG:   op2_scalar.py:1735             table_name=b'CSTM'
DEBUG:   op2_scalar.py:1735             table_name=b'GPLS'
DEBUG:   op2_reader.py:1639           table_name = b'GPLS'
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/nastran/op2_conv.py", line 9, in <module>
    op2.read_op2("results.op2")
  File "/Users/user/PycharmProjects/tdsm/venv/lib/python3.8/site-packages/pyNastran/op2/op2.py", line 553, in read_op2
    table_names = OP2_Scalar.read_op2(self, op2_filename=op2_filename,
  File "/Users/user/PycharmProjects/tdsm/venv/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1588, in read_op2
    table_names = self._read_tables(table_name)
  File "/Users/user/PycharmProjects/tdsm/venv/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1748, in _read_tables
    op2_reader.mapped_tables[table_name]()
  File "/Users/user/PycharmProjects/tdsm/venv/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 1649, in read_gpls
    gpl_gpls, method = Struct(self._endian + b'8si').unpack(data)
struct.error: unpack requires a buffer of 12 bytes

```

If there is any workaround for this error, I would appreciate it.

Thank you.
Hoshino

**Comment by SteveDoyle2** [comment]
You might have an error with the OSMPF1 table as well, but right now you're having an issue reading the GPLS table.,  I've only ever seen one of those tables and am not sure how to generate it.

I need an example to fix it.

**Comment by hoshino23** [comment]
Thank you for your quick reply.
The OP2 file I have is too large to upload, so I'll try to create a smaller example where the error can be reproduced.

**Comment by hoshino23** [comment]
I'm sorry for the delay, but I sent you the sample files via email.

**Comment by SteveDoyle2** [comment]
the bug is fixed.  The GPLS table had a new form.  There was no OSMPF1 table.

**Comment by hoshino23** [comment]
Thank you very much for the fix.
