### ISSUE TITLE
read_op2 failure with  quadratic non-linear elements

### ISSUE THREAD

**Issue by LucaZampieri** [SteveDoyle2/pyNastran#650]
reading an op2 file (containing non-linear quadratic elements, in particular quad8) fails with `OP2.read_op2` 

The failure happens at the reading of the op2 file with OP2.read_op2

This is probably related to:
https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/op2/tables/oee_energy/onr.py#L32   
as cquad8_nonlinear_strain_energy is mentioned.

The line that fails it this one:
https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/op2/tables/oee_energy/onr.py#L437  

## Quickfix for my use case (op2 to vtk file): 
at L437 above, 
```python
try:
    n = self._read_element_strain_energy(data, ndata)
except AttributeError:
    n = 0
```
. This will allow to extract verts, faces and material properties from the op2 file.

## reproduce
I unfortunately cannot share the geometry itself, but I think it is reproducible with other non-linear quadratic elements

## The expected outcome:
Nothing in particular, just for it not to raise an error

## Error trace
```python
File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_geom.py", line 313, in read_op2
    OP2.read_op2(self, op2_filename=op2_filename, combine=combine,
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2.py", line 585, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=self.op2_filename, mode=mode)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_scalar.py", line 1808, in read_op2
    self._read_tables(table_name, table_names)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_scalar.py", line 1981, in _read_tables
    op2_reader.read_results_table()
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_reader.py", line 5669, in read_results_table
    self.read_results_table4()
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_reader.py", line 5694, in read_results_table4
    self._read_subtables()
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_reader.py", line 5895, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/op2_interface/op2_reader.py", line 6049, in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/fortran_format.py", line 82, in _read_subtable_results
    n = table4_parser(data, ndata)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/tables/oee_energy/onr.py", line 494, in _read_onr1_4
    n = 0 # self._read_element_strain_energy(data, ndata)
  File "/home/container_user/workspace/libs/pyNastran/pyNastran/op2/tables/oee_energy/onr.py", line 576, in _read_element_strain_energy
    ), f"etype={self.element_name} isubtable={self.isubtable} eids.min()={eids.min()}"
AttributeError: 'OP2Geom' object has no attribute 'element_name'
```

5. pynstran version 1.4.0

**Comment by SteveDoyle2** [comment]
Unfortunately I need an example.  I run ~40,000 OP2 examples across multiple versions of NX and MSC Nastran, so if it's it's not in the TPL examples, then it's often much more buggy.  It'd already be supported otherwise.

It don't want a large one, which usually also means I don't want a proprietary example.

**Comment by LucaZampieri** [comment]
Makes sense, I apologize then for not being able to provide one now as these files are not created by me but a 3rd party. I will try and request one but cannot guarantee anything in the short term :/ 
(I the mean time I thank you for having made pyNastran which is great! :D )

**Comment by SteveDoyle2** [comment]
Thanks :)

What I'm asking for is (ideally) a 1 element model, so nothing special.

**Comment by SteveDoyle2** [comment]
closing due to innactivity

**Comment by rysciguy** [comment]
I'm having the same issue. It's easy to replicate with a model having only one CQUAD8 element ([single-cquad8.zip](https://github.com/user-attachments/files/22015590/single-cquad8.zip)). I can also fix it with this hacky solution: 

### Modified onr.py
```python
def _read_element_strain_energy(self, data: bytes, ndata: int):
        """
        table_code = 19
        """
        op2 = self.op2
        dt = op2.nonlinear_factor
        n = 0

        element_name = op2.data_code['element_name']
        try:
            # BEGIN HACKY FIX FOR https://github.com/SteveDoyle2/pyNastran/issues/650
            if element_name == "CQUAD8N":
                element_name = 'QUAD8N'
            elif element_name == "CTRIA6N":
                element_name = 'TRIA6'
            # END HACKY FIX
            result_name = RESULT_NAME_MAP[element_name]
        except KeyError:
            raise NotImplementedError('element_name1=%r element_name=%r' % (element_name, op2.data_code['element_name']))
```

### Full Debug Trace

```python
DEBUG:   op2_scalar.py:607            set_subcases - subcases = []
DEBUG:   op2.py:589                   combine=True
DEBUG:   op2.py:590                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1963           op2_filename = 'C:\\scratch\\MODEL-032.op2'
DEBUG:   op2_reader.py:299            date = (8, 27, 25)
DEBUG:   op2_reader.py:382            mode='nx' version='2022.1'
DEBUG:   op2_scalar.py:2172             table_name=b'PVT0'     (PARAM cards)
DEBUG:   op2_scalar.py:2172             table_name=b'CASECC'   (case control)
DEBUG:   op2_scalar.py:2172             table_name=b'EQEXINS'  (internal/external ids (superelement))
DEBUG:   op2_reader.py:653            eqexin idata=(101, 8, 0, 0, 0, 0, 0)
DEBUG:   op2_scalar.py:2172             table_name=b'OGPWG'    (grid point weight)
DEBUG:   op2_scalar.py:2172             table_name=b'EFMFSMS'  (matrix)
DEBUG:   read_matrix.py:168           name=b'EFMFSMS' matrix_num=101 form=2 mrows=6 ncols=1 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'EFMASSS'  (matrix)
DEBUG:   read_matrix.py:168           name=b'EFMASSS' matrix_num=102 form=1 mrows=6 ncols=6 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'RBMASSS'  (matrix)
DEBUG:   read_matrix.py:168           name=b'RBMASSS' matrix_num=103 form=1 mrows=6 ncols=6 tout=2 nvalues=6 g=4444
DEBUG:   op2_scalar.py:2172             table_name=b'EFMFACS'  (matrix)
DEBUG:   read_matrix.py:168           name=b'EFMFACS' matrix_num=104 form=2 mrows=6 ncols=10 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'MPFACS'   (matrix)
DEBUG:   read_matrix.py:168           name=b'MPFACS' matrix_num=101 form=2 mrows=6 ncols=10 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'MEFMASS'  (matrix)
DEBUG:   read_matrix.py:168           name=b'MEFMASS' matrix_num=102 form=2 mrows=6 ncols=10 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'MEFWTS'   (matrix)
DEBUG:   read_matrix.py:168           name=b'MEFWTS' matrix_num=103 form=2 mrows=6 ncols=10 tout=2 nvalues=12 g=10000
DEBUG:   op2_scalar.py:2172             table_name=b'LAMA'     (eigenvalues)
DEBUG:   op2_scalar.py:2172             table_name=b'OUGV1'    (g-set U in CD frame)
DEBUG:   op2_scalar.py:2172             table_name=b'ONRGY1'   (strain energy density)
failed reading b'ONRGY1' isubtable=-4
Traceback (most recent call last):

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\tables\oee_energy\onr.py:475 in _read_element_strain_energy
    result_name = RESULT_NAME_MAP[element_name]

KeyError: 'CQUAD8N'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\git\femap-macros\python scripts\pymassfraction.py:25
    model = read_op2(op2_filename, build_dataframe=False, debug=True, skip_undefined_matrices=True)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2.py:1424 in read_op2
    model.read_op2(op2_filename=op2_filename, build_dataframe=build_dataframe,

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2.py:600 in read_op2
    table_names = OP2_Scalar.read_op2(self, op2_filename=op2_filename,

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py:1998 in read_op2
    self._read_tables(table_name, table_names)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py:2194 in _read_tables
    op2_reader.read_results_table()

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py:3510 in read_results_table
    self.read_results_table4()

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py:3535 in read_results_table4
    self._read_subtables()

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py:3751 in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py:3921 in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\fortran_format.py:180 in _read_subtable_results
    n = table4_parser(data, ndata)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\tables\oee_energy\onr.py:454 in _read_onr1_4
    n = self._read_element_strain_energy(data, ndata)

  File ~\Desktop\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\pyNastran\op2\tables\oee_energy\onr.py:477 in _read_element_strain_energy
    raise NotImplementedError('element_name1=%r element_name=%r' % (element_name, op2.data_code['element_name']))

NotImplementedError: element_name1='CQUAD8N' element_name='CQUAD8N'
```
