### ISSUE TITLE
NotImplementedError raised by read_op2

### ISSUE THREAD

**Issue by hoshino23** [SteveDoyle2/pyNastran#657]
Hello Steve,

Thanks for your great work.
I get a NotImplementedError when loading op2, is there any way to work around this?

Version:
```
Python 3.9.6 
pyNastran 1.4
```

Code:
```
from pyNastran.op2.op2 import OP2
import pyuff
op2 = OP2()
op2.read_op2("sample_a.op2")
uffwrite = pyuff.UFF('sample_a.unv')
...
```

Result:
```
DEBUG:   op2.py:566                   combine=True
DEBUG:   op2.py:567                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1782           op2_filename = 'sample_a.op2'
WARNING: op2_reader.py:320            No mode was set, assuming 'msc'
DEBUG:   op2_reader.py:323            mode = 'msc'
DEBUG:   op2_scalar.py:1969             table_name=b'CSTM'
DEBUG:   op2_scalar.py:1969             table_name=b'GPLS'
DEBUG:   op2_reader.py:2175           table_name = b'GPLS'
DEBUG:   op2_scalar.py:1969             table_name=b'GPDT'
DEBUG:   op2_scalar.py:1969             table_name=b'EPT'
DEBUG:   op2_scalar.py:1969             table_name=b'MPT'
DEBUG:   op2_scalar.py:1969             table_name=b'GEOM2'
DEBUG:   op2_scalar.py:1969             table_name=b'GEOM3'
DEBUG:   op2_scalar.py:1969             table_name=b'GEOM4'
DEBUG:   op2_scalar.py:1969             table_name=b'GEOM1'
DEBUG:   op2_scalar.py:1969             table_name=b'BGPDT'
DEBUG:   op2_scalar.py:1969             table_name=b'OUGV2'
DEBUG:   op2_scalar.py:1969             table_name=b'OSMPF1'
DEBUG:   op2_scalar.py:1969             table_name=b'OASMPF1'
Traceback (most recent call last):
  File "c:\Users\user1\Desktop\Nastran1.4\op2_conv.py", line 4, in <module>    op2.read_op2("sample_a.op2")
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\site-packages\pyNastran\op2\op2.py", line 577, in read_op2
    table_names = OP2_Scalar.read_op2(self, op2_filename=op2_filename,
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1816, in read_op2
    self._read_tables(table_name, table_names)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 2021, in _read_tables
    raise NotImplementedError(msg)
NotImplementedError: Invalid Table = b'OASMPF1'

If you have matrices that you want to read, see:
  model.set_additional_matrices_to_read(matrices)
  matrices = {
      b'BHH' : True,
      b'KHH' : False,
  }  # you want to read some matrices, but not others
  matrices = [b'BHH', b'KHH']  # assumes True

If you the table is a geom/result table, see:
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OUGV1' : [method3, method4],
      b'GEOM4SX' : [method3, method4],
      b'OES1X1' : False,
  }

If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
  methods_dict = {
      b'OUGV1' : [method],
  }
  model.set_additional_generalized_tables_to_read(methods_dict)
```

Thank you.

**Comment by SteveDoyle2** [comment]
The easy way to do it is to get rid fo the table by not writing it in the first place.  That looks to be a writing As-something (assembly?) modal participation factors (MPF).  I'm not familiar with that table, but in general, you can add the table reading yourself using one of the 3 methods mentioned in the error message above.  The such as:

```
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OASMPF1' : False,
  }
```
If you can't code it yourself, then I'd need an example to support it.
