### ISSUE TITLE
Problems writing OP2 files containing RBE elements

### ISSUE THREAD

**Issue by pmoseley** [SteveDoyle2/pyNastran#664]
Hey Steve,

This issue is related to issue #653.

I've been having some compatibility issues with OP2 files containing rigid elements, which I'm writing using pyNastran. I'm taking a MSC OP2 file as an input, making some modifications, and then rewriting it, and MSC Apex/Patran don't recognize the new file as a valid format.

I discovered that actually even pyNastran won't read it's own output back in, although it doesn't note any errors during the write. For example, this code with the attached example files:

```
    print('Reading the input file:',args.inp_file)
    model = OP2Geom()
    model.read_op2(args.inp_file, build_dataframe=False, combine=True)
    model.validate()
    print(model.get_op2_stats(short=True))
    print('Writing the output file:',args.out_file)
    model.write_op2(args.out_file)
    print('Trying to read the output file:',args.out_file)
    model = read_op2(args.out_file,debug=True)
```

Produces the following output:
```
Reading the input file: .\test\RBE_tests\writing_tests\various_rbe_element_test--v2020.op2
INFO:    op2_scalar.py:1780           op2_filename = '.\\test\\RBE_tests\\writing_tests\\various_rbe_element_test--v2020.op2'
WARNING: subcase.py:683               nwords_to_lsem=1000 nwords_to_lsem//4=250
CORD2R         4              0.      0.      0.      0.     -1.      0.
              0.      0.     -1.

CORD2R         5              0.      0.      0.      0.     -1.      0.
              0.      0.     -1.

CORD2R         6              0.      0.      0.      0.     -1.      0.
              0.      0.     -1.

WARNING: subcase.py:683               nwords_to_lsem=1000 nwords_to_lsem//4=250
INFO:    geom_common.py:38            geom skipping BCBODY1 in b'CONTACT'; ndata=64
INFO:    geom_common.py:38            geom skipping BCONECT in b'CONTACT'; ndata=32
INFO:    geom_common.py:38            geom skipping BCONPRG in b'CONTACT'; ndata=336
INFO:    geom_common.py:38            geom skipping BCTABL1 in b'CONTACT'; ndata=12
INFO:    geom_common.py:38            geom skipping BSURF in b'CONTACT'; ndata=48
INFO:    geom_common.py:38            geom skipping BCPARA in b'CONTACT'; ndata=616
op2_results.stress.ctetra_stress[1]
op2_results.stress.chexa_stress[1]
displacements[1]
spc_forces[1]
mpc_forces[1]
grid_point_forces[1]
load_vectors[1]
cbar_stress[1]
cbush_stress[1]
cbush1d_stress_strain[1]

Writing the output file: .\test\RBE_tests\writing_tests\out--pynastran_HEAD--modified.op2
Trying to read the output file: .\test\RBE_tests\writing_tests\out--pynastran_HEAD--modified.op2
DEBUG:   op2_scalar.py:616            set_subcases - subcases = []
DEBUG:   op2.py:567                   combine=True
DEBUG:   op2.py:568                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1780           op2_filename = '.\\test\\RBE_tests\\writing_tests\\out--pynastran_HEAD--modified.op2'
DEBUG:   op2_reader.py:259            date = (8, 4, 21)
DEBUG:   op2_reader.py:336            mode = 'msc'
DEBUG:   op2_scalar.py:1967             table_name=b'GEOM1'
DEBUG:   op2_scalar.py:1967             table_name=b'GEOM2'
DEBUG:   op2_scalar.py:1967             table_name=b'GEOM3'
DEBUG:   op2_scalar.py:1967             table_name=b'GEOM4'
failed reading b'GEOM4' isubtable=-6
Traceback (most recent call last):
  File "D:\DATA_SLOW\TOOLS\StressPostprocessor\StressPostprocessor\read_write_op2.py", line 37, in <module>
    main()
  File "D:\DATA_SLOW\TOOLS\StressPostprocessor\StressPostprocessor\read_write_op2.py", line 30, in main
    model = read_op2(args.out_file,debug=True)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2.py", line 1313, in read_op2
    encoding=encoding)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2.py", line 579, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 1814, in read_op2
    self._read_tables(table_name, table_names)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 1983, in _read_tables
    op2_reader.read_geom_table()  # DIT (agard)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 5888, in read_geom_table
    self._read_subtables()
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 5948, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6033, in _read_subtable_3_4
    record_len = self._get_record_length()
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 5641, in _get_record_length
    markers1 = self.get_nmarkers(1, rewind=True)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 4718, in get_nmarkers
    return self.get_nmarkers4(n, rewind=rewind, macro_rewind=macro_rewind)
  File "c:\users\moseley\.virtualenvs\stresspostprocessor-4gbz0xab\src\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 4743, in get_nmarkers4
    marker, = op2.struct_i.unpack(data)
struct.error: unpack requires a buffer of 4 bytes
```

[various_RBE_tests.zip](https://github.com/SteveDoyle2/pyNastran/files/7301315/various_RBE_tests.zip)

Thanks for all your work on this great tool!

**Comment by SteveDoyle2** [comment]
it had nothing to do with rigid elements.  There was an error when writing SPC cards for MSC Nastran (they use a different format for writing SPCs than NX that adds a dummy 0 value).  They used to be consistent with the NX format, but changed it.
