### ISSUE TITLE
Installation from release (using Anaconda) does not install models folder

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#666]
# Summary
When replicating the examples from [BDF Overview](https://pynastran-git.readthedocs.io/en/1.3/quick_start/bdf_overview.html), the file `solid_bending.bdf` could not be found. This is because there is no folder `models` folder in the installation path of pyNastran.

# Snippet to reproduce the bug
I installed pyNastran following the [installation from release guide](https://pynastran-git.readthedocs.io/en/1.3/installation/installation.html#installation-from-release) using Anaconda and then I ran this script.

```
import pyNastran
import os
from pyNastran.bdf.bdf import BDF

# Store path to model
pkg_path = pyNastran.__path__[0]
test_path = os.path.join(pkg_path, '..', 'models', 'solid_bending')
bdf_filename = os.path.join(test_path, 'solid_bending.bdf')
# Instantiate the model
model = BDF()
model.read_bdf(bdf_filename)
# Print information about the model
print(model.get_bdf_stats())
```

I got the following output instead of the expected information about the bdf file.
```
C:\Users\qa21944\Anaconda3\envs\pynastran\python.exe C:/Users/qa21944/PycharmProjects/pyNastran/BdfOverview/Example1.py
Traceback (most recent call last):
  File "C:/Users/qa21944/PycharmProjects/pyNastran/BdfOverview/Example1.py", line 11, in <module>
    model.read_bdf(bdf_filename)
  File "C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\pyNastran\bdf\bdf.py", line 993, in read_bdf
    check_path(bdf_filename, 'bdf_filename')
  File "C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\pyNastran\utils\__init__.py", line 101, in check_path
    raise FileNotFoundError(msg)
FileNotFoundError: cannot find bdf_filename='C:\\Users\\qa21944\\Anaconda3\\envs\\pynastran\\lib\\site-packages\\pyNastran\\..\\models\\solid_bending\\solid_bending.bdf'
failed: C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\models\solid_bending\solid_bending.bdf
failed: C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\models\solid_bending
failed: C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\models
passed: C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages
passed: C:\Users\qa21944\Anaconda3\envs\pynastran\lib
passed: C:\Users\qa21944\Anaconda3\envs\pynastran
passed: C:\Users\qa21944\Anaconda3\envs
passed: C:\Users\qa21944\Anaconda3
passed: C:\Users\qa21944
passed: C:\Users
passed: C:\

Process finished with exit code 1
```

I have looked for the folder `models` inside the anaconda environment, but I could not find it. Of course I can download the folder from the repository to use the example bdf files, but I was wondering whether it is a bug not to have the `models` folder with the installation from release.

# Versions
pyNastran -> '1.3.3'
python -> '3.8.12'

**Comment by fmamitrotta** [comment]
Understood! Thanks for the clarification
