### ISSUE TITLE
GUI crashes when loading flutter results

### ISSUE THREAD

**Issue by Gypaets** [SteveDoyle2/pyNastran#667]
I've performed a flutter calculation with Nastran and loaded the results with the pyNastranGUI. The files attached are the example from the documentation (modification: negative speed definition to output eigenvectors and specifying OP2 as output format) and the results as OP2. To view the eigenmodes, I select a mode in the `Case/Results` window and push the "Apply" button.
![grafik](https://user-images.githubusercontent.com/19589322/137773911-16fad722-7841-4b2e-8700-2c947471d190.png)

The GUI crashes with the following error:

```
Traceback (most recent call last):
  File "/home/user/src/pyNastran/pyNastran/gui/menus/results_sidebar.py", line 554, in on_apply
    self.update_vtk_window(keys_a, keys_b)
  File "/home/user/src/pyNastran/pyNastran/gui/menus/results_sidebar.py", line 582, in update_vtk_window
    self.parent._set_case(result_name, i, explicit=True)
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 1000, in _set_case
    self.final_grid_update(icase, name, grid_result,
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 1255, in final_grid_update
    self._final_grid_update(icase, name_vector, grid_result_vector, obj, i, res_name,
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 1321, in _final_grid_update
    self._update_grid(vector_data)
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 1432, in _update_grid
    self._update_follower_grids_complex(nodes)
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 1449, in _update_follower_grids_complex
    follower_function(self.nid_map, grid, points, nodes)
  File "/home/user/src/pyNastran/pyNastran/converters/nastran/gui/nastran_io.py", line 7073, in update_conm2s_function
    inid = np.searchsorted(node_ids, nid)
  File "<__array_function__ internals>", line 5, in searchsorted
  File "/usr/local/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 1350, in searchsorted
    return _wrapfunc(a, 'searchsorted', v, side=side, sorter=sorter)
  File "/usr/local/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: object of too small depth for desired array
Aborted (core dumped)
```
[Flutter.zip](https://github.com/SteveDoyle2/pyNastran/files/7367142/Flutter.zip)

**Comment by Gypaets** [comment]
Ok, so the problem was really that I was selecting the mode ` > mode=X; freq=Y Hz` instead of the vector `Eigenvectors T_XYZ`. When I do that the GUI crashes, for the example case I uploaded too.

```
Traceback (most recent call last):
  File "/home/user/src/pyNastran/pyNastran/gui/utils/qt/qtreeview2.py", line 47, in keyPressEvent
    return self.parent.parent.on_apply()
  File "/home/user/src/pyNastran/pyNastran/gui/menus/results_sidebar.py", line 554, in on_apply
    self.update_vtk_window(keys_a, keys_b)
  File "/home/user/src/pyNastran/pyNastran/gui/menus/results_sidebar.py", line 582, in update_vtk_window
    self.parent._set_case(result_name, i, explicit=True)
  File "/home/user/src/pyNastran/pyNastran/gui/qt_files/gui_qt_common.py", line 892, in _set_case
    key = self.case_keys[icase]
TypeError: list indices must be integers or slices, not NoneType
```

I've just wrapped the function causing the crash with a try-except block, feel free to merge it or tell me if I should catch the error in a different way

**Comment by SteveDoyle2** [comment]
tis has been fixed for a while
