### ISSUE TITLE
Fail in reading op2 for autodesk Nastran 2022 on Linux(CentOS7.9)

### ISSUE THREAD

**Issue by mizushimayasunori** [SteveDoyle2/pyNastran#689]
When I try to read the OP2 file obtained from the analysis with autodesk Nastran 2022 for linux, I get the following error message. Is it possible for you to tell me the cause and countermeasure?

Traceback (most recent call last):
  File "op2read.py", line 4, in <module>
    op2.read_op2("jac_dat_0.OP2")
  File "/opt/anaconda3/envs/py-nastran/lib/python3.8/site-packages/pyNastran/op2/op2.py", line 553, in read_op2
    table_names = OP2_Scalar.read_op2(self, op2_filename=op2_filename,
  File "/opt/anaconda3/envs/py-nastran/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1574, in read_op2
    self.op2_reader.read_nastran_version(mode)
  File "/opt/anaconda3/envs/py-nastran/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 236, in read_nastran_version
    mode = _parse_nastran_version(
  File "/opt/anaconda3/envs/py-nastran/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 5729, in _parse_nastran_version
    mode = _parse_nastran_version_8(
  File "/opt/anaconda3/envs/py-nastran/lib/python3.8/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 5785, in _parse_nastran_version_8
    raise RuntimeError('unknown version=%r' % version)
RuntimeError: unknown version=b'NE  0824'

[error.zip](https://github.com/SteveDoyle2/pyNastran/files/8261735/error.zip)

**Comment by mizushimayasunori** [comment]
Hi @SteveDoyle2,
I found an Issue about the same error, which have been closed. (#632)

I downloaded the attachment there and tested it with the fixes described in the Issue.
But , the same error still occurred...

I've attach my input file.
[jac_dat_0.zip](https://github.com/SteveDoyle2/pyNastran/files/8296588/jac_dat_0.zip)

Thank you,

**Comment by mizushimayasunori** [comment]
Hi @SteveDoyle2,
I updated pyNastran from 1.3.3 to 1.4.0.
OP2 data generated by autodesk nastran get readable! 
Thank you for your great work!
