### ISSUE TITLE
nptyping 2.0.0 breaks bdf parsing interface

### ISSUE THREAD

**Issue by timryanb** [SteveDoyle2/pyNastran#691]
It seems that the [nptyping](https://pypi.org/project/nptyping/#history) library, which is a dependency of pyNastran, recently released a new version (2.0.0) on pip that breaks the pyNastran interface.

After doing a fresh pip install of pyNastran and running the pyNastran/bdf/test/bdf_unit_tests.py script, I get the following error:
```
Traceback (most recent call last):
  File "bdf_test.py", line 7, in <module>
    from pyNastran.bdf.test.test_bdf import run_lots_of_files
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/pyNastran/bdf/test/test_bdf.py", line 40, in <module>
    from pyNastran.bdf.bdf import BDF, read_bdf, map_version
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/pyNastran/bdf/bdf.py", line 37, in <module>
    from pyNastran.bdf.bdf_interface.add_card import CARD_MAP
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/pyNastran/bdf/bdf_interface/add_card.py", line 10, in <module>
    from pyNastran.nptyping import NDArray3float, NDArray66float
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/pyNastran/nptyping.py", line 6, in <module>
    NDArray3float = NDArray[(3, ), float]
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/nptyping/ndarray.py", line 73, in __getitem__
    shape_expression, dtype = _get_from_tuple(item)
  File "/Users/trbrooks/miniconda3/envs/pyNastran/lib/python3.8/site-packages/nptyping/ndarray.py", line 128, in _get_from_tuple
    raise InvalidArgumentsError(
nptyping.error.InvalidArgumentsError: Unexpected argument '(3,)', expecting Shape[<ShapeExpression>] or Literal[<ShapeExpression>]
```
But, this error doesn't happen if I manually pip install an older version of nptyping (1.4.4) before pip installing pynastran.
Since, pip will only install the latest version of `nptyping`, if the user doesn't already have one installed, with pyNastran.

In the short-term, this problem can probably be addressed by adding a version upperbound to the `setup.py` i.e. `nptyping<2.0.0`. 

In the long term some of pyNastran's interface may need to be updated to support the nptyping API.

**Comment by SteveDoyle2** [comment]
Looks like the new version was pushed on 2022/4/7 (so yesterday).  I took a quick look at the issue and I think I got it all working.  I have a file that just seems to fix it.

Long term, I may move away from nptyping.  It doesn't bother me so much that they change the API, but numpy has been working on typing.  I've taken a quick look and I think nptyping is easier, but that's sort of a guess.  Regardless, it's still going to be done in a file like:
`NDArray3float = NDArray[(3, ), float]`

I probably should just push a 1.3.4 release with minimal changes.  I think some numpy stuff changed as well, so I'd bundle that in.  1.4 was planned for middle of last year, but I got really busy and the new API cleanup stuff I wasn't sold on is way better.  I've been meaning to do that, but maybe I finally should :)

**Comment by timryanb** [comment]
Thanks for the fast reply @SteveDoyle2!

A minor update to PyPI would be much appreciated, though a major update push would also be welcome! I'm working with a python-based FEA tool (smdogroup/tacs) that uses pynastran as a dependency. So at minimum, we need the fix on PyPI to get our pip install procedure for tacs working again.

**Comment by SteveDoyle2** [comment]
I haven’t released the new build yet.  There are other packages with new
version issues (warnings in numpy and errors in h5py).  I decided to just
do an official bug release.  That should be done within the week.

**Comment by SteveDoyle2** [comment]
1.3.4 has been released.  Definitely a long week :)
