### ISSUE TITLE
Bug with Viewer geometry editor

### ISSUE THREAD

**Issue by jpdeslich** [SteveDoyle2/pyNastran#715]
Using Version: 1.4.0+dev.e18d7cdd9, on Mac M1, I am getting the following error when I select the edit geometry menu or use the keyboard short cut.

dt_load = 0.39 sec = 0.01 min
need to add '_create_nastran_tools_and_menu_items'
Traceback (most recent call last):
  File "/Path_To_pyNastran/pyNastran/pyNastran/gui/menus/edit_geometry_properties/edit_geometry_properties_object.py", line 54, in edit_geometry_properties
    self._edit_geometry_properties = EditGeometryProperties(data, win_parent=self.gui)
  File "/Path_To_pyNastran/pyNastran/pyNastran/gui/menus/edit_geometry_properties/manage_actors.py", line 311, in __init__
    self.opacity_slider_edit.setValue(opacity * 10)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Abort trap: 6

**Comment by SteveDoyle2** [comment]
Wow...git is worse than I thought...I didn't close it...

I'm not sure what happened.  I wonder if you're a weird state.  I rounded that value and stuck an int around it, so that should fix it.  Let me know
