### ISSUE TITLE
read_op2 with load_geometry=True fails because of NLPARM card validation

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#741]
# Summary
I'm doing some nonlinear analyses with SOL 106 and I'm using NLPARM and NLPCI cards. For the MAXBIS field of the NLPARM card, the MSC Nastran manual says that the value has to be between -10 and 10. However, this is simply not true. I had to allow the nonlinear solver to perform a large number of bisections for some particular reasons, so I tried with MAXBIS=20 and the analysis ran perfectly wihout any fatal error.

However, when I try to read the op2 file using `read_op2` with `load_geometry=True`, this fails with the following error:

```
failed reading b'MPT' isubtable=-4
Traceback (most recent call last):
  File "c:\Users\qa21944\Github\phd-jupyter-notebooks\notebooks\PlotLoadDisplacementDiagram.py", line 13, in <module>
    op2_output = read_op2(op2_filename=op2_filepath, load_geometry=True, debug=None)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2.py", line 1318, in read_op2
    model = read_op2_geom(
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_geom.py", line 101, in read_op2_geom
    model.read_op2(op2_filename=op2_filename, build_dataframe=build_dataframe,
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_geom.py", line 318, in read_op2
    OP2.read_op2(self, op2_filename=op2_filename, combine=combine,
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2.py", line 591, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=self.op2_filename, mode=mode)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 1987, in read_op2      
    self._read_tables(table_name, table_names)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 2179, in _read_tables  
    op2_reader.read_geom_table()  # DIT (agard)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6562, in read_geom_table
    self._read_subtables()
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6631, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6793, in _read_subtable_3_4
    unused_n = table4_parser(data, ndata)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\tables\geom\mpt.py", line 35, in read_mpt_4
    return self.op2._read_geom_4(self.mpt_map, data, ndata)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\op2_interface\op2_common.py", line 699, in _read_geom_4   
    n = func(data, n)  # gets all the grid/mat cards
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\tables\geom\mpt.py", line 1469, in _read_nlparm
    n, nlparms = self._read_nlparm_80(data, n)
  File "c:\users\qa21944\github\pynastran\pyNastran\op2\tables\geom\mpt.py", line 1586, in _read_nlparm_80        
    nlparm = NLPARM.add_op2_data(out)
  File "c:\users\qa21944\github\pynastran\pyNastran\bdf\cards\dynamic.py", line 1204, in add_op2_data
    nlparm.validate()
  File "c:\users\qa21944\github\pynastran\pyNastran\bdf\cards\dynamic.py", line 1100, in validate
    assert -10 <= self.max_bisect <= 10, self.get_stats()
AssertionError: ---NLPARM---
  comment : ''
  conv   : 'PW'
  dt     : 0.0
  eps_p  : 0.0010000000474974513
  eps_u  : 0.0010000000474974513
  eps_w  : 1.0000000116860974e-07
  fstress : 0.20000000298023224
  int_out : 'YES'
  kmethod : 'ITER'
  kstep  : 1
  ls_tol : 0.5
  max_bisect : 20
  max_div : 3
  max_iter : 3
  max_ls : 4
  max_qn : 25
  max_r  : 20.0
  ninc   : 5
  nlparm_id : 2
  rtol_b : 20.0
  type   : 'NLPARM'
```

If I understand correctly the error message, this is caused by the fact that the code tries to validate the NLPARM card by checking that MAXBIS is between -10 and 10, and of course in my case it fails. Is it possible to get rid of this check, at least for positive values, since the analysis appears to run without fatal errors? I'm happy to try more values of MAXBIS if needed.

# Reproduction
Read the op2 file at [this link](https://drive.google.com/file/d/1ViwDhuYPWF-yq2ksFA3d9TQZmN1vq6d8/view?usp=drive_link) using:
```
read_op2(op2_filename="natural_path_verification_maxiter3_desiter3.op2", load_geometry=True, debug=None)
```

# Versions
`platform.python_version()` --> 3.9.16
`pyNastran.__version__` --> 1.4.0+dev.no.checksum.error ([this commit](https://github.com/SteveDoyle2/pyNastran/commit/dc06aa01c0cddc125c6e3b582445825fcf75eeb3))

**Comment by SteveDoyle2** [comment]
Nastran is so weird.  That card has been so difficult to try to parse
correctly (moreso in binary).  Does that change the result vs MAXBIS=10) or
does it just cap out?

Also, it’s not required to load the geometry from the op2, so you can skip
that check.

**Comment by fmamitrotta** [comment]
Nastran is very weird indeed. It's not the first time in my small experience that something in the manual turns out not to be true. Once I found a parameter whose default was a value according to the manual, another value according to the support engineer I was speaking to and in the end it turned out to be a completely different value!

Anyway, yes I need to set MAXBIS>10 in my case, otherwise the analysis does not converge because it exceeds the number of maximum bisections. And I also need to load the geometry because I need to make some deformation plots.

Do you want me to check different values of MAXBIS to modify the check?

I believe there is no reason why the user should not be allowed to set the max number of bisections as large as they want, unless this hits Nastran's precision. But it should be the user's responsibility to have a sensible value in my opinion.

**Comment by SteveDoyle2** [comment]
You should see the PBEAM ;). It gets even harder with NX, so at some point
I just give up and set the default to None.

The ranges are useful for identifying a changing format.  How about +/- 100?

**Comment by fmamitrotta** [comment]
It sounds good! I've just done a couple of tests and the analysis runs without fatal error for both MAXBIS=-100 and MAXBIS=100. Shall I modify the code and open a pull request?

**Comment by SteveDoyle2** [comment]
I did the push.  Seemed like it was adequately excessive.
