### ISSUE TITLE
Unable to Launch 1.4.0_2024-2-29 Executable on Windows 10

### ISSUE THREAD

**Issue by sudoDrive** [SteveDoyle2/pyNastran#771]
Downloaded the version 1.4.0_2024-2-29 Windows executable from https://sourceforge.net/projects/pynastran/files/?source=navbar/

However, I get the following error when I try to launch

>D:\>pyNastranGUI.exe
supported_formats = ['nastran', 'abaqus', 'bedge', 'surf', 'ugrid', 'ugrid3d', 'cart3d', 'fast', 'lawgs', 'panair', 'shabp', 'stl', 'su2', 'tecplot', 'tetgen', 'usm3d', 'avl', 'vtk']
Traceback (most recent call last):
  File "gui.py", line 114, in <module>
  File "gui.py", line 110, in cmd_line
  File "main_window.py", line 162, in __init__
  File "gui_common.py", line 1529, in setup_gui
  File "gui_common.py", line 293, in set_tools
  File "gui_common.py", line 458, in get_recent_file_tools
UnboundLocalError: cannot access local variable 'ifile' where it is not associated with a value
[1560] Failed to execute script 'gui' due to unhandled exception!

Have no problems getting version 1.3.4_2022-5-30 to launch.

**Comment by SteveDoyle2** [comment]
If you see issue 761 or the forum, there’s a file to fix it.  On my phone,
so hard to provide a link

**Comment by SteveDoyle2** [comment]
https://github.com/SteveDoyle2/pyNastran/issues/761
